### ISSUE TITLE
Input fields on a web page have no length limits

### ISSUE THREAD

**Issue by Milord-Freeman** [flipperdevices/blackmagic-esp32-s2#19]
On small devices, when opening a web page with settings to enter Wi-Fi connection data, there is an event to increase the input field when typing characters. There is a limit of 3 characters, but there is no limit on the maximum length, which is why when typing long ssids and passwords, the layout breaks, making the save data button inaccessible. In theory, a good solution would be to make an adaptive design depending on the available sizes, but as a hotfix, I will only suggest [adding an additional check](https://github.com/flipperdevices/blackmagic-esp32-s2/blob/473bdd4d0952a731ae1abd7ac0644401fed65eaa/components/svelte-portal/src/Input.svelte#L12) for the second magic number, which means the maximum length. Something like this:
```
function text_input() {
  this.size = this.value.length > 3 ? this.value.length < 20 ? this.value.length : 20 : 3;
  value = this.value;
}
```

<details>
  <summary>Before</summary>
  
![изображение](https://user-images.githubusercontent.com/23146879/205467113-07fca8ac-25bf-4ac1-9e99-0eb5b050a8ed.png)

</details>

<details>
  <summary>After</summary>
  
![изображение](https://user-images.githubusercontent.com/23146879/205467205-397f2840-e8bb-455a-972d-c6001aa0f5f2.png)

</details>

**Comment by DrZlo13** [comment]
I made a [mobile-friendly UI](https://github.com/flipperdevices/blackmagic-esp32-s2/pull/18/commits/a905cdefa06dd80966561f152540dea5c15abe29).

![IMG_20230208_202206_229](https://user-images.githubusercontent.com/4784169/217606871-cf9d8520-c280-489e-8770-96ac379ca9f3.jpg)
