### ISSUE TITLE
mdns does not work in AP mode

### ISSUE THREAD

**Issue by 11wanqin** [flipperdevices/blackmagic-esp32-s2#24]
The mdns works fine in STA mode, but it seems does not work in AP mode.
if move "network_post_init();" in front of  “switch(wifi_mode)”，the mdns can work fine in AP and STA mode.
![image](https://user-images.githubusercontent.com/65119313/219868020-98d1ed85-5420-48dc-a3da-d5279e748d2d.png)
![image](https://user-images.githubusercontent.com/65119313/219868193-9f5afb86-954d-419a-b0e5-4100f9b0ae3a.png)
![image](https://user-images.githubusercontent.com/65119313/219868483-15f73cf2-5c71-418d-8431-318e90cc5046.png)
![image](https://user-images.githubusercontent.com/65119313/219868652-e1928b39-0cc6-4974-b5a9-e0fbbfaa6c94.png)

**Comment by DrZlo13** [comment]
Thanks for the report, we'll fix it as soon as we have time.

**Comment by 11wanqin** [comment]
Thank you for getting back to me. This is an excellent open-source project; I hope it can improve.

**Comment by DrZlo13** [comment]
I am reopening this issue to track it down.

**Comment by DrZlo13** [comment]
Fixed in #29
