### ISSUE TITLE
Read logs?

### ISSUE THREAD

**Issue by lo00l** [flipperdevices/blackmagic-esp32-s2#26]
Hi there,
What tools should I use to read logs?

I can see the logging is performed via uart 7th pin. So I use my USB-to-TTL converter connecting IO7 pin to TX pin of my converter. The I run `screen /dev/cu.usbserial-2130 57600`.
Everything works except log messaged are printed with really strange formatting (see screenshot). It makes it hardy readable.
Can I fix it somehow? Thank you.
<img width="1725" alt="Screenshot 2023-03-20 at 10 47 33 AM" src="https://user-images.githubusercontent.com/6896941/226235585-adb28a54-b3d5-48cd-bbc4-27eac5fcf3ac.png">

**Comment by lomalkin** [comment]
Hello, you should reset terminal first via command `reset`, and try again with screen.

**Comment by DrZlo13** [comment]
Also, UART baud rate is 230400

**Comment by DrZlo13** [comment]
I use miniterm that comes with pyserial, like `python3 -m serial.tools.miniterm --raw /dev/cu.usbmodem112203 57600`

**Comment by lo00l** [comment]
@lomalkin running `reset` before `screen` didn't help  :(

@DrZlo13 yeah, with miniterm everything works great, thank you 👍
