### ISSUE TITLE
OTA update

### ISSUE THREAD

**Issue by FalsePhilosopher** [flipperdevices/blackmagic-esp32-s2#30]
Add an OTA function to this and an update setting to initiate an update and select if you wanna update from SD or OTA then proceed with the update. If SD load the file browser to select an update file and launch the SD updater. If OTA select a network to join and enter a pass or add it to the settings file and have it download the resources from the web update servers an launch the updater.

**Comment by DrZlo13** [comment]
We are working on it, I will write back when something is implemented.

**Comment by skotopes** [comment]
We have `./fbt devboard_flash` in main firmware repo that manages updates. Also there is an app in flipper application catalog that can do that.

As for now there are no plans to implement OTA for wifi devboard
