### ISSUE TITLE
Missing blackmagic/esp32-s2 module schematics

### ISSUE THREAD

**Issue by adamm** [flipperdevices/blackmagic-esp32-s2#7]
There are schematics provided for the older flipperzero-devboard-stlinkv3, but nothing for this blackmagic/esp32-s2 module.

(Sorry to post this Issue in this code repo -- unsure where else to ask :)

Thanks!

**Comment by DrZlo13** [comment]
Thanks for you issue. Our project overwhelmed me a little so I apologize for the delay.

We will publish the schematic soon.

**Comment by DrZlo13** [comment]
Solved in #10
